apiVersion: v1
kind: Service
metadata:
  name: adote-application
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "kubernetes.io/role/elb=1"
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: adote-application
  type: LoadBalancer
