spring:
  application:
    name: "Adote Application"
  datasource:
    driverClassName: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/adote'
    username: 'adote'
    password: 'adote'
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

management:
  health:
    db:
      enabled: true
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always

aws:
  credentials:
    accessKey: ''
    secretKey: ''
  region: ''
  bucketName: ''
